deploy:
  runs-on: ubuntu-latest
  needs: build
  environment:
    name: 'Production'
    url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
  
  steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: node-app

    - name: Unzip artifact for deployment
      run: unzip release.zip

    # 🔹 LIMPIAR ARCHIVOS EXISTENTES EN AZURE (ANTES DEL DEPLOY)
    - name: Clean existing files on Azure Web App
      run: |
        curl -X POST "https://${{ secrets.AZURE_WEBAPP_NAME }}.scm.azurewebsites.net/api/command" \
        -u ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_151250504D874704AE13032E752B863E }} \
        -H "Content-Type: application/json" \
        -d '{ "command": "rm -rf /home/site/wwwroot/*" }'

    - name: 'Deploy to Azure Web App'
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'kizeoApp'
        slot-name: 'Production'
        package: .
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_151250504D874704AE13032E752B863E }}
